name: Env铆o de Notificaci贸n CI

# Se activa cuando hay un push a la rama main
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest  # Entorno de ejecuci贸n (Linux)

    steps:
      - name: Env铆a notificaci贸n a ntfy.sh
        run: |
          curl -d " Nueva actualizaci贸n en el repositorio! Rama: main. Commit: ${{ github.sha }}. Mensaje: ${{ github.event.head_commit.message }}" \
          https://ntfy.sh/devops-itla
        # Esto env铆a un mensaje con detalles del commit usando curl    